/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess

import edu.austral.dissis.chess.gui.*
import javafx.application.Application
import javafx.application.Application.launch
import javafx.scene.Scene
import javafx.stage.Stage
import src.Chess.ChessGameEngine
import src.InternationalCheckers.InternationalCheckersGameEngine
import src.StandardCheckers.StandardCheckersGameEngine


fun main() {
    launch(ChessGameApplication::class.java)
}

class ChessGameApplication : Application() {
    private val internationalCheckersGameEngine = InternationalCheckersGameEngine()
    private val StandardCheckersGameEngine = StandardCheckersGameEngine()
    private val chessGameEngine = ChessGameEngine()
    private val gameEngine = SimpleGameEngine()
    private val imageResolver = CachedImageResolver(DefaultImageResolver())

    companion object {
        const val GameTitle = "Chess"
    }

    override fun start(primaryStage: Stage) {
        primaryStage.title = GameTitle

        //val root = createGameViewFrom(internationalCheckersGameEngine, imageResolver)
        val root = createGameViewFrom(chessGameEngine, imageResolver)
        //val root = GameView(chessGameEngine, imageResolver)
        //val root = GameView(gameEngine, imageResolver)
        primaryStage.scene = Scene(root)

        primaryStage.show()
    }
}